apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service
  namespace: default
  labels:
    app: yolo
    tier: backend
spec:
  selector:
    app: yolo
    tier: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP