apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
  namespace: default
  labels:
    app: yolo
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo
      tier: frontend
  template:
    metadata:
      labels:
        app: yolo
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: joyrose/yolo-frontend:1.0.0
          ports:
            - containerPort: 80
