apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend-service
  namespace: default
  labels:
    app: yolo
    tier: frontend
spec:
  selector:
    app: yolo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer